# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.1.0")
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.1.0...3.28)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::VirtualKeyboardQml)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::VirtualKeyboardQml
add_library(Qt6::VirtualKeyboardQml SHARED IMPORTED)

set_target_properties(Qt6::VirtualKeyboardQml PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_VIRTUALKEYBOARDQML_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtVirtualKeyboardQml;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Gui;Qt6::Qml;Qt6::Quick;Qt6::VirtualKeyboard"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/./metatypes/qt6virtualkeyboardqml_metatypes.json>"
  QT_DISABLED_PRIVATE_FEATURES "vkb_sensitive_debug;cerence_sdk;cerence_hwr;cerence_hwr_alphabetic;cerence_hwr_cjk;cerence_xt9;system_hunspell;3rdparty_hunspell;hunspell;myscript;vkb_no_bundle_pinyin;vkb_no_bundle_tcime;example_hwr;vkb_lang_zh_HK"
  QT_DISABLED_PUBLIC_FEATURES "vkb_record_trace_input;vkb_arrow_keynavigation;vkb_no_builtin_style;vkb_retro_style;vkb_bundle_cerence;vkb_bundle_cerence_hwr;vkb_bundle_cerence_xt9;vkb_cerence_xt9_debug;vkb_cerence_xt9_9key_layouts;vkb_cerence_static"
  QT_ENABLED_PRIVATE_FEATURES "openwnn;pinyin;tcime;zhuyin;cangjie;hangul;thai;vkb_lang_ar_AR;vkb_lang_bg_BG;vkb_lang_cs_CZ;vkb_lang_da_DK;vkb_lang_de_DE;vkb_lang_el_GR;vkb_lang_en_GB;vkb_lang_en_US;vkb_lang_es_ES;vkb_lang_es_MX;vkb_lang_et_EE;vkb_lang_fa_FA;vkb_lang_fi_FI;vkb_lang_fr_CA;vkb_lang_fr_FR;vkb_lang_he_IL;vkb_lang_hi_IN;vkb_lang_hr_HR;vkb_lang_hu_HU;vkb_lang_id_ID;vkb_lang_it_IT;vkb_lang_lv_LV;vkb_lang_ja_JP;vkb_lang_ko_KR;vkb_lang_ms_MY;vkb_lang_nb_NO;vkb_lang_nl_NL;vkb_lang_pl_PL;vkb_lang_pt_BR;vkb_lang_pt_PT;vkb_lang_ro_RO;vkb_lang_ru_RU;vkb_lang_sk_SK;vkb_lang_sl_SI;vkb_lang_sq_AL;vkb_lang_sr_SP;vkb_lang_sv_SE;vkb_lang_th_TH;vkb_lang_tr_TR;vkb_lang_uk_UA;vkb_lang_vi_VN;vkb_lang_zh_CN;vkb_lang_zh_TW"
  QT_ENABLED_PUBLIC_FEATURES "vkb_desktop;vkb_layouts;vkb_default_style"
  QT_QMAKE_PRIVATE_CONFIG ""
  QT_QMAKE_PUBLIC_CONFIG ""
  QT_QMAKE_PUBLIC_QT_CONFIG ""
  _qt_config_module_name "virtualkeyboardqml"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtVirtualKeyboardQml"
  _qt_module_interface_name "VirtualKeyboardQml"
  _qt_module_relative_include_dir "../../../include/QtVirtualKeyboardQml"
  _qt_package_name "Qt6VirtualKeyboardQml"
  _qt_package_version "6.10.0"
  _qt_private_module_target_name "VirtualKeyboardQmlPrivate"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_class_name "QtQuick_VirtualKeyboardPlugin"
  _qt_qml_module_has_plugin "TRUE"
  _qt_qml_module_installed_plugin_target "Qt6::qtvkbplugin"
  _qt_qml_module_installed_qmldir_path "qml/QtQuick/VirtualKeyboard/qmldir"
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_plugin_target "qtvkbplugin"
  _qt_qml_module_target_path "QtQuick/VirtualKeyboard"
  _qt_qml_module_uri "QtQuick.VirtualKeyboard"
  _qt_qml_module_version "6.10"
  _qt_sbom_spdx_id "SPDXRef-Package-qtvirtualkeyboard-qt-module-VirtualKeyboardQml"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtvirtualkeyboard-6.10.0.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtvirtualkeyboard-6.10.0"
  _qt_sbom_spdx_repo_project_name_lowercase "qtvirtualkeyboard"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/Qt6VirtualKeyboardQmlTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::VirtualKeyboard" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
