QT.webenginequickdelegatesqml_private.VERSION = 6.6.2
QT.webenginequickdelegatesqml_private.name = QtWebEngineQuickDelegatesQml
QT.webenginequickdelegatesqml_private.module =
QT.webenginequickdelegatesqml_private.libs = $$QT_MODULE_LIB_BASE
QT.webenginequickdelegatesqml_private.includes = 
QT.webenginequickdelegatesqml_private.frameworks = 
QT.webenginequickdelegatesqml_private.depends = webenginequickdelegatesqml
QT.webenginequickdelegatesqml_private.uses = 
QT.webenginequickdelegatesqml_private.module_config = v2 internal_module
QT.webenginequickdelegatesqml_private.enabled_features = 
QT.webenginequickdelegatesqml_private.disabled_features = 
