QT.qdoccatchconversionsprivate_private.VERSION = 6.6.2
QT.qdoccatchconversionsprivate_private.name = QtQDocCatchConversionsPrivate
QT.qdoccatchconversionsprivate_private.module =
QT.qdoccatchconversionsprivate_private.libs = $$QT_MODULE_LIB_BASE
QT.qdoccatchconversionsprivate_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQDocCatchConversionsPrivate/6.6.2 $$QT_MODULE_INCLUDE_BASE/QtQDocCatchConversionsPrivate/6.6.2/QtQDocCatchConversionsPrivate
QT.qdoccatchconversionsprivate_private.frameworks = 
QT.qdoccatchconversionsprivate_private.depends = 
QT.qdoccatchconversionsprivate_private.uses = 
QT.qdoccatchconversionsprivate_private.module_config = v2 internal_module
QT.qdoccatchconversionsprivate_private.enabled_features = 
QT.qdoccatchconversionsprivate_private.disabled_features = 
