QT.quickstudioeventsimulator_private.VERSION = 6.2.4
QT.quickstudioeventsimulator_private.name = QtQuickStudioEventSimulator
QT.quickstudioeventsimulator_private.module =
QT.quickstudioeventsimulator_private.libs = $$QT_MODULE_LIB_BASE
QT.quickstudioeventsimulator_private.includes = 
QT.quickstudioeventsimulator_private.frameworks = 
QT.quickstudioeventsimulator_private.depends = quickstudioeventsimulator
QT.quickstudioeventsimulator_private.uses = 
QT.quickstudioeventsimulator_private.module_config = v2 internal_module
QT.quickstudioeventsimulator_private.enabled_features = 
QT.quickstudioeventsimulator_private.disabled_features = 
