QT.flowview_private.VERSION = 6.2.4
QT.flowview_private.name = QtFlowView
QT.flowview_private.module =
QT.flowview_private.libs = $$QT_MODULE_LIB_BASE
QT.flowview_private.includes = 
QT.flowview_private.frameworks = 
QT.flowview_private.depends = flowview
QT.flowview_private.uses = 
QT.flowview_private.module_config = v2 internal_module
QT.flowview_private.enabled_features = 
QT.flowview_private.disabled_features = 
