/* This file was generated by syncqt. */
#ifndef QT_QTAXSERVER_VERSION_H
#define QT_QTAXSERVER_VERSION_H

#define QTAXSERVER_VERSION_STR "6.6.2"

#define QTAXSERVER_VERSION 0x060602

#endif // QT_QTAXSERVER_VERSION_H
