/* This file was generated by syncqt. */
#ifndef QT_QTQMLCORE_VERSION_H
#define QT_QTQMLCORE_VERSION_H

#define QTQMLCORE_VERSION_STR "6.6.1"

#define QTQMLCORE_VERSION 0x060601

#endif // QT_QTQMLCORE_VERSION_H
