set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_ENABLED_PUBLIC_FEATURES "$<$<OR:$<CONFIG:Debug>>:>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_DISABLED_PUBLIC_FEATURES "$<$<OR:$<CONFIG:Debug>>:>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_ENABLED_PRIVATE_FEATURES "$<$<OR:$<CONFIG:Debug>>:scxml;scxml_qml;scxml_ecmascriptdatamodel;statemachine;statemachine_qml;qeventtransition>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_DISABLED_PRIVATE_FEATURES "$<$<OR:$<CONFIG:Debug>>:>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_QMAKE_PUBLIC_CONFIG "$<$<OR:$<CONFIG:Debug>>:>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_QMAKE_PRIVATE_CONFIG "$<$<OR:$<CONFIG:Debug>>:>")
set_property(TARGET Qt6::ScxmlGlobalPrivate APPEND PROPERTY INTERFACE_QT_QMAKE_PUBLIC_QT_CONFIG "$<$<OR:$<CONFIG:Debug>>:>")
