# CMake generated Testfile for 
# Source directory: C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test
# Build directory: C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(driver "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_driver.exe")
  set_tests_properties(driver PROPERTIES  ENVIRONMENT "CLIENT_SIDE_ENCRYPTION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption;URI_OPTIONS_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/uri-options" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;229;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(driver "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_driver.exe")
  set_tests_properties(driver PROPERTIES  ENVIRONMENT "CLIENT_SIDE_ENCRYPTION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption;URI_OPTIONS_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/uri-options" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;229;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(driver NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_logging.exe")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;230;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_logging.exe")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;230;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(instance "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_instance.exe")
  set_tests_properties(instance PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;231;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(instance "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_instance.exe")
  set_tests_properties(instance PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;231;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(instance NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(crud_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_crud_specs.exe")
  set_tests_properties(crud_specs PROPERTIES  ENVIRONMENT "CRUD_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/crud/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;232;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(crud_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_crud_specs.exe")
  set_tests_properties(crud_specs PROPERTIES  ENVIRONMENT "CRUD_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/crud/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;232;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(crud_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gridfs_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_gridfs_specs.exe")
  set_tests_properties(gridfs_specs PROPERTIES  ENVIRONMENT "GRIDFS_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/gridfs" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;233;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gridfs_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_gridfs_specs.exe")
  set_tests_properties(gridfs_specs PROPERTIES  ENVIRONMENT "GRIDFS_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/gridfs" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;233;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(gridfs_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(client_side_encryption_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_client_side_encryption_specs.exe")
  set_tests_properties(client_side_encryption_specs PROPERTIES  ENVIRONMENT "CLIENT_SIDE_ENCRYPTION_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;234;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(client_side_encryption_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_client_side_encryption_specs.exe")
  set_tests_properties(client_side_encryption_specs PROPERTIES  ENVIRONMENT "CLIENT_SIDE_ENCRYPTION_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;234;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(client_side_encryption_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(command_monitoring_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_command_monitoring_specs.exe")
  set_tests_properties(command_monitoring_specs PROPERTIES  ENVIRONMENT "COMMAND_MONITORING_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/command-monitoring" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;235;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(command_monitoring_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_command_monitoring_specs.exe")
  set_tests_properties(command_monitoring_specs PROPERTIES  ENVIRONMENT "COMMAND_MONITORING_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/command-monitoring" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;235;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(command_monitoring_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(transactions_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_transactions_specs.exe")
  set_tests_properties(transactions_specs PROPERTIES  ENVIRONMENT "TRANSACTIONS_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/transactions/legacy;WITH_TRANSACTION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/with_transaction" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;236;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(transactions_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_transactions_specs.exe")
  set_tests_properties(transactions_specs PROPERTIES  ENVIRONMENT "TRANSACTIONS_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/transactions/legacy;WITH_TRANSACTION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/with_transaction" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;236;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(transactions_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(retryable_reads_spec "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_retryable_reads_specs.exe")
  set_tests_properties(retryable_reads_spec PROPERTIES  ENVIRONMENT "RETRYABLE_READS_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-reads/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;237;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(retryable_reads_spec "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_retryable_reads_specs.exe")
  set_tests_properties(retryable_reads_spec PROPERTIES  ENVIRONMENT "RETRYABLE_READS_LEGACY_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-reads/legacy" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;237;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(retryable_reads_spec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(read_write_concern_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_read_write_concern_specs.exe")
  set_tests_properties(read_write_concern_specs PROPERTIES  ENVIRONMENT "READ_WRITE_CONCERN_OPERATION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/read-write-concern/operation" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;238;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(read_write_concern_specs "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_read_write_concern_specs.exe")
  set_tests_properties(read_write_concern_specs PROPERTIES  ENVIRONMENT "READ_WRITE_CONCERN_OPERATION_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/read-write-concern/operation" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;238;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(read_write_concern_specs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unified_format_spec "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_unified_format_spec.exe")
  set_tests_properties(unified_format_spec PROPERTIES  ENVIRONMENT "CHANGE_STREAMS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/change-streams/unified;CLIENT_SIDE_ENCRYPTION_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption/unified;COLLECTION_MANAGEMENT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/collection-management;CRUD_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/crud/unified;INDEX_MANAGEMENT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/index-management;RETRYABLE_READS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-reads/unified/;RETRYABLE_WRITES_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-writes/unified/;SESSION_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/sessions/unified/;TRANSACTIONS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/transactions/unified;UNIFIED_FORMAT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/unified-format;VERSIONED_API_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/versioned-api" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;239;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unified_format_spec "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_unified_format_spec.exe")
  set_tests_properties(unified_format_spec PROPERTIES  ENVIRONMENT "CHANGE_STREAMS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/change-streams/unified;CLIENT_SIDE_ENCRYPTION_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/client_side_encryption/unified;COLLECTION_MANAGEMENT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/collection-management;CRUD_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/crud/unified;INDEX_MANAGEMENT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/index-management;RETRYABLE_READS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-reads/unified/;RETRYABLE_WRITES_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/retryable-writes/unified/;SESSION_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/sessions/unified/;TRANSACTIONS_UNIFIED_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/transactions/unified;UNIFIED_FORMAT_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/unified-format;VERSIONED_API_TESTS_PATH=C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/data/versioned-api" _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;239;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(unified_format_spec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(versioned_api "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Debug/test_versioned_api.exe")
  set_tests_properties(versioned_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;240;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(versioned_api "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/OTBuild/src/mongocxx/test/Release/test_versioned_api.exe")
  set_tests_properties(versioned_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;240;add_test;C:/Users/JWagner/Downloads/mongo-cxx-driver-r3.10.0/src/mongocxx/test/CMakeLists.txt;0;")
else()
  add_test(versioned_api NOT_AVAILABLE)
endif()
