/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "6.6.1"

#define QTCHARTS_VERSION 0x060601

#endif // QT_QTCHARTS_VERSION_H
