/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "6.6.2"

#define QTSENSORS_VERSION 0x060602

#endif // QT_QTSENSORS_VERSION_H
