/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "6.6.1"

#define QT3DQUICK_VERSION 0x060601

#endif // QT_QT3DQUICK_VERSION_H
