# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source;C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64")
set(CPACK_CMAKE_GENERATOR "Visual Studio 15 2017 Win64")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "ZIP")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64;gmsh;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files/gmsh")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "gmsh")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "gmsh")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/doc/WELCOME.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "3D finite element mesh generator with built-in CAD engine and post-processor")
set(CPACK_PACKAGE_EXECUTABLE "gmsh")
set(CPACK_PACKAGE_FILE_NAME "gmsh-git-Windows64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "gmsh")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "gmsh")
set(CPACK_PACKAGE_NAME "gmsh")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Christophe Geuzaine and Jean-Francois Remacle")
set(CPACK_PACKAGE_VERSION "4.8.0")
set(CPACK_PACKAGE_VERSION_MAJOR "4")
set(CPACK_PACKAGE_VERSION_MINOR "8")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/doc/WELCOME.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/doc/WELCOME.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64;/CVS/;/.svn;/.git;~$;DS_Store$;GmshConfig.h$;GmshVersion.h$;/benchmarks/;/tmp/;/bin/;/lib/;/nightly/;GPATH;GRTAGS;GSYMS;GTAGS;/HTML/;/contrib/3M/;/contrib/Parasolid/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "gmsh-git-source")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "TRUE")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Daten/Projekte/SimulationPlatform/Third_Party_Libraries/gmsh/gmsh-4.8.0-source/build_Win64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
