/* This file was generated by syncqt. */
#ifndef QT_QTLOTTIE_VERSION_H
#define QT_QTLOTTIE_VERSION_H

#define QTLOTTIE_VERSION_STR "6.10.0"

#define QTLOTTIE_VERSION 0x0601000

#endif // QT_QTLOTTIE_VERSION_H
