# CMake generated Testfile for 
# Source directory: C:/OT/ThirdParty/gmsh/gmsh-4.13.1
# Build directory: C:/OT/ThirdParty/gmsh/gmsh-4.13.1/build_Win64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(../examples/api/square.geo "./gmsh" "../examples/api/square.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/api/square.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/baffles.geo "./gmsh" "../examples/boolean/baffles.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/baffles.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/boolean.geo "./gmsh" "../examples/boolean/boolean.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/boolean.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/chamfer.geo "./gmsh" "../examples/boolean/chamfer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/chamfer.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/coherence.geo "./gmsh" "../examples/boolean/coherence.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/coherence.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/compsolid.geo "./gmsh" "../examples/boolean/compsolid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/compsolid.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/compsolid2.geo "./gmsh" "../examples/boolean/compsolid2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/compsolid2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/extend_field.geo "./gmsh" "../examples/boolean/extend_field.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/extend_field.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/extrude.geo "./gmsh" "../examples/boolean/extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/extrude.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/extrude2.geo "./gmsh" "../examples/boolean/extrude2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/extrude2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fillet.geo "./gmsh" "../examples/boolean/fillet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fillet.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fillet2.geo "./gmsh" "../examples/boolean/fillet2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fillet2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fillet3.geo "./gmsh" "../examples/boolean/fillet3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fillet3.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fillet4.geo "./gmsh" "../examples/boolean/fillet4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fillet4.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fillet_chamfer.geo "./gmsh" "../examples/boolean/fillet_chamfer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fillet_chamfer.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fleur.geo "./gmsh" "../examples/boolean/fleur.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fleur.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/fragment_numbering.geo "./gmsh" "../examples/boolean/fragment_numbering.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/fragment_numbering.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/hybrid_occ_builtin.geo "./gmsh" "../examples/boolean/hybrid_occ_builtin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/hybrid_occ_builtin.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/hyperboloid.geo "./gmsh" "../examples/boolean/hyperboloid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/hyperboloid.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/import.geo "./gmsh" "../examples/boolean/import.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/import.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/import2.geo "./gmsh" "../examples/boolean/import2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/import2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/intersect_line_volume.geo "./gmsh" "../examples/boolean/intersect_line_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/intersect_line_volume.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/mesh_size_per_volume.geo "./gmsh" "../examples/boolean/mesh_size_per_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/mesh_size_per_volume.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/neuron.geo "./gmsh" "../examples/boolean/neuron.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/neuron.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/number_of_tets.geo "./gmsh" "../examples/boolean/number_of_tets.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/number_of_tets.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/periodic.geo "./gmsh" "../examples/boolean/periodic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/periodic.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/periodic_embedded.geo "./gmsh" "../examples/boolean/periodic_embedded.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/periodic_embedded.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/pipe.geo "./gmsh" "../examples/boolean/pipe.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/pipe.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/primitives.geo "./gmsh" "../examples/boolean/primitives.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/primitives.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/revolve.geo "./gmsh" "../examples/boolean/revolve.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/revolve.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/revolve2.geo "./gmsh" "../examples/boolean/revolve2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/revolve2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/shell_sewing.geo "./gmsh" "../examples/boolean/shell_sewing.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/shell_sewing.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple.geo "./gmsh" "../examples/boolean/simple.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple2.geo "./gmsh" "../examples/boolean/simple2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple3.geo "./gmsh" "../examples/boolean/simple3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple3.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple4.geo "./gmsh" "../examples/boolean/simple4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple4.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple5.geo "./gmsh" "../examples/boolean/simple5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple5.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple6.geo "./gmsh" "../examples/boolean/simple6.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple6.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/simple7.geo "./gmsh" "../examples/boolean/simple7.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/simple7.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/slicer.geo "./gmsh" "../examples/boolean/slicer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/slicer.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/slicer_surfaces.geo "./gmsh" "../examples/boolean/slicer_surfaces.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/slicer_surfaces.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/spherical_surf.geo "./gmsh" "../examples/boolean/spherical_surf.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/spherical_surf.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/spline.geo "./gmsh" "../examples/boolean/spline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/spline.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/step_assembly.geo "./gmsh" "../examples/boolean/step_assembly.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/step_assembly.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/surface_filling.geo "./gmsh" "../examples/boolean/surface_filling.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/surface_filling.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/thicksolid.geo "./gmsh" "../examples/boolean/thicksolid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/thicksolid.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/thrusections.geo "./gmsh" "../examples/boolean/thrusections.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/thrusections.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/transfinite.geo "./gmsh" "../examples/boolean/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/transfinite.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/transform.geo "./gmsh" "../examples/boolean/transform.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/transform.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/boolean/twist.geo "./gmsh" "../examples/boolean/twist.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/boolean/twist.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/post_processing/compute_area_volume.geo "./gmsh" "../examples/post_processing/compute_area_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/post_processing/compute_area_volume.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/post_processing/lowmem-anim.geo "./gmsh" "../examples/post_processing/lowmem-anim.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/post_processing/lowmem-anim.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/post_processing/plot2d.geo "./gmsh" "../examples/post_processing/plot2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/post_processing/plot2d.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/post_processing/right_scale_centered.geo "./gmsh" "../examples/post_processing/right_scale_centered.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/post_processing/right_scale_centered.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/post_processing/view_groups.geo "./gmsh" "../examples/post_processing/view_groups.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/post_processing/view_groups.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/antenna.geo "./gmsh" "../examples/simple_geo/antenna.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/antenna.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/cone.geo "./gmsh" "../examples/simple_geo/cone.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/cone.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/cube.geo "./gmsh" "../examples/simple_geo/cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/cube.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/filter.geo "./gmsh" "../examples/simple_geo/filter.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/filter.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/hex.geo "./gmsh" "../examples/simple_geo/hex.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/hex.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/homology.geo "./gmsh" "../examples/simple_geo/homology.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/homology.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/indheat.geo "./gmsh" "../examples/simple_geo/indheat.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/indheat.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/machine.geo "./gmsh" "../examples/simple_geo/machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/machine.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/piece-extr-rec.geo "./gmsh" "../examples/simple_geo/piece-extr-rec.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/piece-extr-rec.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/piece-extr.geo "./gmsh" "../examples/simple_geo/piece-extr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/piece-extr.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/piece.geo "./gmsh" "../examples/simple_geo/piece.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/piece.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/pripyrtet.geo "./gmsh" "../examples/simple_geo/pripyrtet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/pripyrtet.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/sphere-discrete.geo "./gmsh" "../examples/simple_geo/sphere-discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/sphere-discrete.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/sphere.geo "./gmsh" "../examples/simple_geo/sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/sphere.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/splines.geo "./gmsh" "../examples/simple_geo/splines.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/splines.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/square_regular.geo "./gmsh" "../examples/simple_geo/square_regular.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/square_regular.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/tower.geo "./gmsh" "../examples/simple_geo/tower.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/tower.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/simple_geo/transfinite.geo "./gmsh" "../examples/simple_geo/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/simple_geo/transfinite.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/struct/Exists_GetForced.geo "./gmsh" "../examples/struct/Exists_GetForced.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/struct/Exists_GetForced.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../examples/struct/struct.geo "./gmsh" "../examples/struct/struct.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../examples/struct/struct.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t1.geo "./gmsh" "../tutorials/t1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t1.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t10.geo "./gmsh" "../tutorials/t10.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t10.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t11.geo "./gmsh" "../tutorials/t11.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t11.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t12.geo "./gmsh" "../tutorials/t12.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t12.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t13.geo "./gmsh" "../tutorials/t13.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t13.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t14.geo "./gmsh" "../tutorials/t14.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t14.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t15.geo "./gmsh" "../tutorials/t15.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t15.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t16.geo "./gmsh" "../tutorials/t16.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t16.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t17.geo "./gmsh" "../tutorials/t17.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t17.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t18.geo "./gmsh" "../tutorials/t18.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t18.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t19.geo "./gmsh" "../tutorials/t19.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t19.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t2.geo "./gmsh" "../tutorials/t2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t2.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t20.geo "./gmsh" "../tutorials/t20.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t20.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t21.geo "./gmsh" "../tutorials/t21.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t21.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t3.geo "./gmsh" "../tutorials/t3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t3.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t4.geo "./gmsh" "../tutorials/t4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t4.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t5.geo "./gmsh" "../tutorials/t5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t5.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t6.geo "./gmsh" "../tutorials/t6.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t6.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t7.geo "./gmsh" "../tutorials/t7.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t7.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t8.geo "./gmsh" "../tutorials/t8.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t8.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(../tutorials/t9.geo "./gmsh" "../tutorials/t9.geo" "-3" "-nopopup" "-o" "./tmp.msh")
set_tests_properties(../tutorials/t9.geo PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2258;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t1_cpp "t1_cpp" "-nopopup")
set_tests_properties(t1_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t10_cpp "t10_cpp" "-nopopup")
set_tests_properties(t10_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t11_cpp "t11_cpp" "-nopopup")
set_tests_properties(t11_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t12_cpp "t12_cpp" "-nopopup")
set_tests_properties(t12_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t13_cpp "t13_cpp" "-nopopup")
set_tests_properties(t13_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t14_cpp "t14_cpp" "-nopopup")
set_tests_properties(t14_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t15_cpp "t15_cpp" "-nopopup")
set_tests_properties(t15_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t16_cpp "t16_cpp" "-nopopup")
set_tests_properties(t16_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t17_cpp "t17_cpp" "-nopopup")
set_tests_properties(t17_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t18_cpp "t18_cpp" "-nopopup")
set_tests_properties(t18_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t19_cpp "t19_cpp" "-nopopup")
set_tests_properties(t19_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t2_cpp "t2_cpp" "-nopopup")
set_tests_properties(t2_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t20_cpp "t20_cpp" "-nopopup")
set_tests_properties(t20_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t21_cpp "t21_cpp" "-nopopup")
set_tests_properties(t21_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t3_cpp "t3_cpp" "-nopopup")
set_tests_properties(t3_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t4_cpp "t4_cpp" "-nopopup")
set_tests_properties(t4_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t5_cpp "t5_cpp" "-nopopup")
set_tests_properties(t5_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t6_cpp "t6_cpp" "-nopopup")
set_tests_properties(t6_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t7_cpp "t7_cpp" "-nopopup")
set_tests_properties(t7_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t8_cpp "t8_cpp" "-nopopup")
set_tests_properties(t8_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t9_cpp "t9_cpp" "-nopopup")
set_tests_properties(t9_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x1_cpp "x1_cpp" "-nopopup")
set_tests_properties(x1_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x2_cpp "x2_cpp" "-nopopup")
set_tests_properties(x2_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x3_cpp "x3_cpp" "-nopopup")
set_tests_properties(x3_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x4_cpp "x4_cpp" "-nopopup")
set_tests_properties(x4_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x5_cpp "x5_cpp" "-nopopup")
set_tests_properties(x5_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x6_cpp "x6_cpp" "-nopopup")
set_tests_properties(x6_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(x7_cpp "x7_cpp" "-nopopup")
set_tests_properties(x7_cpp PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t1_c "t1_c" "-nopopup")
set_tests_properties(t1_c PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t16_c "t16_c" "-nopopup")
set_tests_properties(t16_c PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t2_c "t2_c" "-nopopup")
set_tests_properties(t2_c PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
add_test(t6_c "t6_c" "-nopopup")
set_tests_properties(t6_c PROPERTIES  _BACKTRACE_TRIPLES "C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;2278;add_test;C:/OT/ThirdParty/gmsh/gmsh-4.13.1/CMakeLists.txt;0;")
subdirs("src/common")
subdirs("src/numeric")
subdirs("src/geo")
subdirs("src/mesh")
subdirs("src/solver")
subdirs("src/post")
subdirs("src/plugin")
subdirs("src/parser")
subdirs("contrib/onelab")
subdirs("contrib/ANN")
subdirs("contrib/ALGLIB")
subdirs("contrib/DiscreteIntegration")
subdirs("contrib/kbipack")
subdirs("contrib/MathEx")
subdirs("contrib/tinyxml2")
subdirs("contrib/metis")
subdirs("contrib/voro++")
subdirs("contrib/HighOrderMeshOptimizer")
subdirs("contrib/MeshOptimizer")
subdirs("contrib/MeshQualityOptimizer")
subdirs("contrib/domhex")
subdirs("contrib/QuadTri")
subdirs("contrib/blossom")
subdirs("contrib/nii2mesh")
subdirs("contrib/untangle")
subdirs("contrib/Netgen")
subdirs("contrib/bamg")
subdirs("contrib/hxt")
subdirs("contrib/QuadMeshingTools")
subdirs("contrib/WinslowUntangler")
