/* This file was generated by syncqt. */
#ifndef QT_QTOPCUA_VERSION_H
#define QT_QTOPCUA_VERSION_H

#define QTOPCUA_VERSION_STR "6.6.2"

#define QTOPCUA_VERSION 0x060602

#endif // QT_QTOPCUA_VERSION_H
