#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKDE" for configuration "Release"
set_property(TARGET TKDE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDE PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDE.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDE.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDE )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDE.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDE.dll" )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSBase.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSBase "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSBase.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSBase.dll" )

# Import target "TKDESTEP" for configuration "Release"
set_property(TARGET TKDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDESTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDESTEP.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDESTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDESTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDESTEP "${_IMPORT_PREFIX}/win64/vc14/lib/TKDESTEP.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDESTEP.dll" )

# Import target "TKXCAF" for configuration "Release"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXCAF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXCAF "${_IMPORT_PREFIX}/win64/vc14/lib/TKXCAF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXCAF.dll" )

# Import target "TKDEIGES" for configuration "Release"
set_property(TARGET TKDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEIGES.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEIGES "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEIGES.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEIGES.dll" )

# Import target "TKDESTL" for configuration "Release"
set_property(TARGET TKDESTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDESTL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDESTL.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDESTL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDESTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDESTL "${_IMPORT_PREFIX}/win64/vc14/lib/TKDESTL.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDESTL.dll" )

# Import target "TKDEVRML" for configuration "Release"
set_property(TARGET TKDEVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEVRML PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEVRML.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEVRML.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEVRML )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEVRML "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEVRML.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEVRML.dll" )

# Import target "TKRWMesh" for configuration "Release"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKRWMesh.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKRWMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKRWMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKRWMesh "${_IMPORT_PREFIX}/win64/vc14/lib/TKRWMesh.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKRWMesh.dll" )

# Import target "TKDECascade" for configuration "Release"
set_property(TARGET TKDECascade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDECascade PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDECascade.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDECascade.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDECascade )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDECascade "${_IMPORT_PREFIX}/win64/vc14/lib/TKDECascade.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDECascade.dll" )

# Import target "TKBinXCAF" for configuration "Release"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKBinXCAF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKBinXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinXCAF "${_IMPORT_PREFIX}/win64/vc14/lib/TKBinXCAF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKBinXCAF.dll" )

# Import target "TKXmlXCAF" for configuration "Release"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXmlXCAF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXmlXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlXCAF "${_IMPORT_PREFIX}/win64/vc14/lib/TKXmlXCAF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXmlXCAF.dll" )

# Import target "TKDEOBJ" for configuration "Release"
set_property(TARGET TKDEOBJ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEOBJ PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEOBJ.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEOBJ.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEOBJ )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEOBJ "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEOBJ.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEOBJ.dll" )

# Import target "TKDEGLTF" for configuration "Release"
set_property(TARGET TKDEGLTF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEGLTF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEGLTF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEGLTF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEGLTF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEGLTF "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEGLTF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEGLTF.dll" )

# Import target "TKDEPLY" for configuration "Release"
set_property(TARGET TKDEPLY APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEPLY PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEPLY.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEPLY.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEPLY )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEPLY "${_IMPORT_PREFIX}/win64/vc14/lib/TKDEPLY.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDEPLY.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
