#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKDraw" for configuration "Release"
set_property(TARGET TKDraw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDraw PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDraw.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDraw.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDraw )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDraw "${_IMPORT_PREFIX}/win64/vc14/lib/TKDraw.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDraw.dll" )

# Import target "TKTopTest" for configuration "Release"
set_property(TARGET TKTopTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTopTest PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKTopTest.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKTopTest.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTopTest )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTopTest "${_IMPORT_PREFIX}/win64/vc14/lib/TKTopTest.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKTopTest.dll" )

# Import target "TKOpenGlTest" for configuration "Release"
set_property(TARGET TKOpenGlTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOpenGlTest PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKOpenGlTest.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKOpenGlTest.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKOpenGlTest )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKOpenGlTest "${_IMPORT_PREFIX}/win64/vc14/lib/TKOpenGlTest.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKOpenGlTest.dll" )

# Import target "TKViewerTest" for configuration "Release"
set_property(TARGET TKViewerTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKViewerTest PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKViewerTest.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKViewerTest.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKViewerTest )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKViewerTest "${_IMPORT_PREFIX}/win64/vc14/lib/TKViewerTest.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKViewerTest.dll" )

# Import target "TKOpenGlesTest" for configuration "Release"
set_property(TARGET TKOpenGlesTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOpenGlesTest PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKOpenGlesTest.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKOpenGlesTest.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKOpenGlesTest )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKOpenGlesTest "${_IMPORT_PREFIX}/win64/vc14/lib/TKOpenGlesTest.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKOpenGlesTest.dll" )

# Import target "TKD3DHostTest" for configuration "Release"
set_property(TARGET TKD3DHostTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKD3DHostTest PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKD3DHostTest.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKD3DHostTest.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKD3DHostTest )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKD3DHostTest "${_IMPORT_PREFIX}/win64/vc14/lib/TKD3DHostTest.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKD3DHostTest.dll" )

# Import target "TKXSDRAW" for configuration "Release"
set_property(TARGET TKXSDRAW APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAW PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAW.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAW.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAW )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAW "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAW.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAW.dll" )

# Import target "TKDCAF" for configuration "Release"
set_property(TARGET TKDCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKDCAF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKDCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDCAF "${_IMPORT_PREFIX}/win64/vc14/lib/TKDCAF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKDCAF.dll" )

# Import target "TKXDEDRAW" for configuration "Release"
set_property(TARGET TKXDEDRAW APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDEDRAW PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXDEDRAW.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXDEDRAW.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXDEDRAW )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXDEDRAW "${_IMPORT_PREFIX}/win64/vc14/lib/TKXDEDRAW.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXDEDRAW.dll" )

# Import target "TKTObjDRAW" for configuration "Release"
set_property(TARGET TKTObjDRAW APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTObjDRAW PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKTObjDRAW.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKTObjDRAW.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTObjDRAW )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTObjDRAW "${_IMPORT_PREFIX}/win64/vc14/lib/TKTObjDRAW.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKTObjDRAW.dll" )

# Import target "TKQADraw" for configuration "Release"
set_property(TARGET TKQADraw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKQADraw PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKQADraw.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKQADraw.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKQADraw )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKQADraw "${_IMPORT_PREFIX}/win64/vc14/lib/TKQADraw.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKQADraw.dll" )

# Import target "TKIVtkDraw" for configuration "Release"
set_property(TARGET TKIVtkDraw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKIVtkDraw PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKIVtkDraw.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKIVtkDraw.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKIVtkDraw )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKIVtkDraw "${_IMPORT_PREFIX}/win64/vc14/lib/TKIVtkDraw.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKIVtkDraw.dll" )

# Import target "TKXSDRAWDE" for configuration "Release"
set_property(TARGET TKXSDRAWDE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWDE PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWDE.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWDE.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWDE )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWDE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWDE.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWDE.dll" )

# Import target "TKXSDRAWGLTF" for configuration "Release"
set_property(TARGET TKXSDRAWGLTF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWGLTF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWGLTF.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWGLTF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWGLTF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWGLTF "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWGLTF.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWGLTF.dll" )

# Import target "TKXSDRAWIGES" for configuration "Release"
set_property(TARGET TKXSDRAWIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWIGES.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWIGES "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWIGES.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWIGES.dll" )

# Import target "TKXSDRAWOBJ" for configuration "Release"
set_property(TARGET TKXSDRAWOBJ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWOBJ PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWOBJ.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWOBJ.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWOBJ )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWOBJ "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWOBJ.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWOBJ.dll" )

# Import target "TKXSDRAWPLY" for configuration "Release"
set_property(TARGET TKXSDRAWPLY APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWPLY PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWPLY.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWPLY.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWPLY )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWPLY "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWPLY.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWPLY.dll" )

# Import target "TKXSDRAWSTEP" for configuration "Release"
set_property(TARGET TKXSDRAWSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWSTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWSTEP.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWSTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWSTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWSTEP "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWSTEP.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWSTEP.dll" )

# Import target "TKXSDRAWSTL" for configuration "Release"
set_property(TARGET TKXSDRAWSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWSTL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWSTL.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWSTL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWSTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWSTL "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWSTL.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWSTL.dll" )

# Import target "TKXSDRAWVRML" for configuration "Release"
set_property(TARGET TKXSDRAWVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSDRAWVRML PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWVRML.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWVRML.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSDRAWVRML )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSDRAWVRML "${_IMPORT_PREFIX}/win64/vc14/lib/TKXSDRAWVRML.lib" "${_IMPORT_PREFIX}/win64/vc14/bin/TKXSDRAWVRML.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
