set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_ENABLED_PUBLIC_FEATURES "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:fullqthelp>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_DISABLED_PUBLIC_FEATURES "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_ENABLED_PRIVATE_FEATURES "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:assistant;clang;clang_rtti;qdoc;designer;distancefieldgenerator;kmap2qmap;linguist;pixeltool;qdbus;qev;qtattributionsscanner;qtdiag;qtplugininfo>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_DISABLED_PRIVATE_FEATURES "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_QMAKE_PUBLIC_CONFIG "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_QMAKE_PRIVATE_CONFIG "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:>")
set_property(TARGET Qt6::Tools PROPERTY INTERFACE_QT_QMAKE_PUBLIC_QT_CONFIG "$<$<OR:$<CONFIG:RelWithDebInfo>,$<NOT:$<BOOL:$<CONFIG>>>>:>")
include("${CMAKE_CURRENT_LIST_DIR}/Qt6ToolsExtraProperties-Debug.cmake")