QMAKE_INCDIR_OPENXR_LOADER = C:/Users/qt/work/qt/qtquick3d/src/3rdparty/openxr/include
QMAKE_DEFINES_OPENXR_LOADER = 
QMAKE_LIBS_OPENXR_LOADER_RELEASE = $$[QT_INSTALL_LIBS/get]/Qt6BundledOpenXR.lib
QMAKE_LIBS_OPENXR_LOADER_DEBUG = $$[QT_INSTALL_LIBS/get]/Qt6BundledOpenXRd.lib
