/* This file was generated by syncqt. */
#ifndef QT_QTWEBVIEW_VERSION_H
#define QT_QTWEBVIEW_VERSION_H

#define QTWEBVIEW_VERSION_STR "6.10.0"

#define QTWEBVIEW_VERSION 0x0601000

#endif // QT_QTWEBVIEW_VERSION_H
