/* This file was generated by syncqt. */
#ifndef QT_QTACTIVEQT_VERSION_H
#define QT_QTACTIVEQT_VERSION_H

#define QTACTIVEQT_VERSION_STR "6.6.2"

#define QTACTIVEQT_VERSION 0x060602

#endif // QT_QTACTIVEQT_VERSION_H
